// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {
    '404': { id: '404', path: '*', parentId: 'DocLayout' },
    'dumi-context-layout': {
      id: 'dumi-context-layout',
      path: '/',
      isLayout: true
    },
    DocLayout: {
      id: 'DocLayout',
      path: '/',
      parentId: 'dumi-context-layout',
      isLayout: true
    },
    DemoLayout: {
      id: 'DemoLayout',
      path: '/',
      parentId: 'dumi-context-layout',
      isLayout: true
    },
    './docs/guide': {
      path: 'guide',
      id: './docs/guide',
      parentId: 'DocLayout'
    },
    './docs/index': { path: '', id: './docs/index', parentId: 'DocLayout' },
    './docs/test': { path: 'test', id: './docs/test', parentId: 'DocLayout' },
    '../packages/hooks/src/use-boolean/index': {
      path: 'hooks/src/use-boolean',
      id: '../packages/hooks/src/use-boolean/index',
      parentId: 'DocLayout'
    },
    '../packages/hooks/src/use-unmount/index': {
      path: 'hooks/src/use-unmount',
      id: '../packages/hooks/src/use-unmount/index',
      parentId: 'DocLayout'
    },
    '../packages/hooks/src/use-update/index': {
      path: 'hooks/src/use-update',
      id: '../packages/hooks/src/use-update/index',
      parentId: 'DocLayout'
    },
    '../packages/hooks/index': {
      path: 'hooks',
      id: '../packages/hooks/index',
      parentId: 'DocLayout'
    },
    'demo-render': {
      id: 'demo-render',
      path: '~demos/:id',
      parentId: 'DemoLayout',
      prerender: false
    }
  } as const;
  return {
    routes,
    routeComponents: {
      '404': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.11__node_modules__dumi__dist__client__pages__404" */ '/Users/lance/dev/github/react-template-taro/node_modules/.pnpm/dumi@2.1.11/node_modules/dumi/dist/client/pages/404.js'
          )
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */ '/Users/lance/dev/github/react-template-taro/docs/.dumi/tmp/dumi/theme/ContextWrapper.tsx'
          )
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.11__node_modules__dumi__theme-default__layouts__DocLayout__index" */ '/Users/lance/dev/github/react-template-taro/node_modules/.pnpm/dumi@2.1.11/node_modules/dumi/theme-default/layouts/DocLayout/index.js'
          )
      ),
      DemoLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi-theme-mobile_2.0.4_dumi_2.1.11__node_modules__dumi-theme-mobile__dist__layouts__DemoLayout" */ '/Users/lance/dev/github/react-template-taro/node_modules/.pnpm/dumi-theme-mobile@2.0.4_dumi@2.1.11/node_modules/dumi-theme-mobile/dist/layouts/DemoLayout.js'
          )
      ),
      './docs/guide': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide.md" */ '/Users/lance/dev/github/react-template-taro/docs/docs/guide.md'
          )
      ),
      './docs/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__index.md" */ '/Users/lance/dev/github/react-template-taro/docs/docs/index.md'
          )
      ),
      './docs/test': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__test.md" */ '/Users/lance/dev/github/react-template-taro/docs/docs/test.md'
          )
      ),
      '../packages/hooks/src/use-boolean/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__hooks__src__use-boolean__index.md" */ '/Users/lance/dev/github/react-template-taro/packages/hooks/src/use-boolean/index.md'
          )
      ),
      '../packages/hooks/src/use-unmount/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__hooks__src__use-unmount__index.md" */ '/Users/lance/dev/github/react-template-taro/packages/hooks/src/use-unmount/index.md'
          )
      ),
      '../packages/hooks/src/use-update/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__hooks__src__use-update__index.md" */ '/Users/lance/dev/github/react-template-taro/packages/hooks/src/use-update/index.md'
          )
      ),
      '../packages/hooks/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__hooks__index.md" */ '/Users/lance/dev/github/react-template-taro/packages/hooks/index.md'
          )
      ),
      'demo-render': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.11__node_modules__dumi__dist__client__pages__Demo__index" */ '/Users/lance/dev/github/react-template-taro/node_modules/.pnpm/dumi@2.1.11/node_modules/dumi/dist/client/pages/Demo/index.js'
          )
      )
    }
  };
}
