// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/lance/dev/github/react-template-taro/node_modules/.pnpm/dumi@2.1.11/node_modules/dumi/theme-default/slots/NotFound/index.js';
