// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/lance/dev/github/react-template-taro/node_modules/.pnpm/dumi-theme-mobile@2.0.4_dumi@2.1.11/node_modules/dumi-theme-mobile/dist/builtins/Previewer/index.js';
